=== joeuint/crazymarket/pysim/stocks/company.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "CrazyMarket Company",
    "type": "object",
    "properties": {
        "ticker": {
            "type": "string",
            "description": "The stock ticker symbol for the company."
        },
        "company_name": {
            "type": "string",
            "description": "The full name of the company."
        },
        "biography": {
            "type": "string",
            "description": "A brief biography or description of the company."
        },
        "ipo": {
            "type": "integer",
            "description": "Opening Price in cents"
        }
    },
    "required": ["ticker", "company_name", "biography", "ipo"]
}

=== joeuint/crazymarket/pysim/stocks/Banana.json
{
    "$schema": "company.schema.json",
    "ticker": "BNAN",
    "company_name": "Banana Corp.",
    "biography": "Banana is the leading provider of technology. It's named after a fruit so what can go wrong. They create consumer electronics such as the WePhone, WeBook, and the WeMac. We make products with the highest price. No one can compete with our incredibly high prices. The best part, people still buy it. So join us in cutting costs while raising prices to the moon.",
    "ipo": 5000
}

=== joeuint/crazymarket/pysim/stocks/Picon.json
{
    "$schema": "./company.schema.json",
    "ticker": "PICN",
    "company_name": "Picon Inc.",
    "biography": "We make computer memory chips and capitalize on every oppertunity. We would ditch our customers in a heartbeat the moment we get a chance of becoming the most valuable company for even 20 seconds. We firmly believe that short-term high growth is better than long-term steady growth. That stuff's for nerds anyways. We will jump in on any bandwagon even if we know it'll collapse just to make our stock price go up slightly higher. Yes our customers hate us, no we don't care.",
    "ipo": 75000
}

=== joeuint/crazymarket/pysim/stocks/Poogle.json
{
    "$schema": "./company.schema.json",
    "ticker": "POG",
    "company_name": "Poogle",
    "biography": "We are Poogle. We started off by creating a product that people love. The whole world uses. Our motto was, \"Don't be evil\". But that was the past lol. Our motto is now now \"Don't be evil unless it makes hella cash\". We strive to be a company that shareholders love and the average person hates. That's basically every company but we want to be the worst. We sell all of our customers data for a huge profit so other evil companies can advertise to them. Isn't that great? In fact, we've replaced our dividends with the full information and identity of random people who never consented to it. One stock = one person's data. We aren't all bad though. We also fund our competition ~so we don't get sued for anti-trust~ out of the goodness of our own hearts.",
    "ipo": 123030
}
